<a href="https://colab.research.google.com/github/TheMonarch00/Projects/blob/main/Minor_Project_preprocessing_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

In [ ]:
%ls /content/drive/MyDrive/Internship_ml/image_data/

bikes/  planes/  trucks/


In [ ]:
import os
import numpy as np
import pandas as pd
import matplotlib.pyplot as plt
from skimage.transform import resize
from skimage.io import imread


In [ ]:

target = []
images = [] #matrix format of the image
flat_data = []
DATADIR = '/content/drive/MyDrive/Internship_ml/image_data'

CATAGORIES = ['bikes','planes','trucks']

for i in CATAGORIES:
  class_target = CATAGORIES.index(i) #label encoded the target value
  path = os.path.join(DATADIR,i)
  for img in os.listdir(path):
    img_array = imread(os.path.join(path,img))
    img_resized = resize(img_array,(400,400,3))
    flat_data.append(img_resized.flatten())
    images.append(img_resized)
    target.append(class_target)
    #print(img_resized.shape)
flat_data = np.array(flat_data)
target = np.array(target)
images = np.array(images)

In [ ]:
df = pd.DataFrame(flat_data)
df['Target'] = target
df

0         1         2  ...    479998    479999  Target
0   1.000000  1.000000  1.000000  ...  1.000000  1.000000       0
1   1.000000  1.000000  1.000000  ...  1.000000  1.000000       0
2   1.000000  1.000000  1.000000  ...  1.000000  1.000000       0
3   1.000000  1.000000  1.000000  ...  1.000000  1.000000       0
4   0.247059  0.470588  0.772549  ...  0.248646  0.470901       0
..       ...       ...       ...  ...       ...       ...     ...
85  0.039059  0.243059  0.427294  ...  0.343922  0.378118       2
86  0.502059  0.627549  0.866765  ...  0.424044  0.397202       2
87  0.649020  0.731373  0.845098  ...  0.364706  0.368627       2
88  1.000000  1.000000  1.000000  ...  1.000000  1.000000       2
89  1.000000  1.000000  1.000000  ...  1.000000  1.000000       2

[90 rows x 480001 columns]

In [ ]:
unique,count = np.unique(target, return_counts=True)


In [ ]:
from sklearn.model_selection import train_test_split
x_train,x_test,y_train,y_test = train_test_split(flat_data, target, test_size = 0.3, random_state = 1, stratify = target)

In [ ]:
from sklearn.svm import SVC
from sklearn.model_selection import GridSearchCV
svc = SVC()
parameters = {
    'kernel' : ['linear','rbf'],
    'C' : [0.1,1,10,100]
}
cv = GridSearchCV(svc,parameters,cv = 5)
cv.fit(x_train,y_train)
cv.best_params_

{'C': 0.1, 'kernel': 'linear'}

In [ ]:
model = SVC(C=0.1, kernel='linear')
model.fit(x_train,y_train)

SVC(C=0.1, break_ties=False, cache_size=200, class_weight=None, coef0=0.0,
    decision_function_shape='ovr', degree=3, gamma='scale', kernel='linear',
    max_iter=-1, probability=False, random_state=None, shrinking=True,
    tol=0.001, verbose=False)

In [ ]:
y_pred = model.predict(x_test)
y_pred

array([1, 0, 2, 1, 0, 2, 0, 1, 0, 0, 2, 0, 1, 0, 1, 2, 2, 0, 1, 0, 1, 2,
       0, 1, 0, 0, 2])

In [ ]:
from sklearn.metrics import accuracy_score,confusion_matrix,classification_report
confusion_matrix(y_pred,y_test)

array([[9, 0, 3],
       [0, 8, 0],
       [0, 1, 6]])

In [ ]:
accuracy_score(y_test,y_pred)

0.8518518518518519

In [ ]:
print(classification_report(y_pred,y_test))

              precision    recall  f1-score   support

           0       1.00      0.75      0.86        12
           1       0.89      1.00      0.94         8
           2       0.67      0.86      0.75         7

    accuracy                           0.85        27
   macro avg       0.85      0.87      0.85        27
weighted avg       0.88      0.85      0.85        27



In [ ]:
from sklearn.neighbors import KNeighborsClassifier
model1 = KNeighborsClassifier()
model1.fit(x_train,y_train)

KNeighborsClassifier(algorithm='auto', leaf_size=30, metric='minkowski',
                     metric_params=None, n_jobs=None, n_neighbors=5, p=2,
                     weights='uniform')

In [ ]:
y_pred = model.predict(x_test)
y_pred

array([1, 0, 2, 1, 0, 2, 0, 1, 0, 0, 2, 0, 1, 0, 1, 2, 2, 0, 1, 0, 1, 2,
       0, 1, 0, 0, 2])

In [ ]:
confusion_matrix(y_pred,y_test)

array([[9, 0, 3],
       [0, 8, 0],
       [0, 1, 6]])